### ISSUE TITLE
Value Error when calling _Yamcha.new_chunker

### ISSUE THREAD

**Issue by kavin26** [kento1218/yamcha#2]
Hi,

I've been porting my python (version : 2.7) scripts to python 3.x (version:3.7.6). In one of my scripts i've been calling Yamcha to extract Entity Name-Value pairs from text files.

I'd build python package by running the following commands inside the python folder
`python setup.py build`
`python setup.py install`

After this, when i called my python script to generate name-value pairs, i was thrown an error, 
`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kavin/app-repositories/all-projects/datamd_ml/Scripts/extraction.py", line 372, in <module>
    e = Extraction()
  File "/home/kavin/app-repositories/all-projects/datamd_ml/Scripts/extraction.py", line 45, in __init__
    YamCha.Chunker(['', '-m', BASE_MODEL_PATH % '/Models/Extraction/entity_extraction_svm.model']),
  File "/home/kavin/app-repositories/all-projects/datamd_ml/Scripts/YamCha.py", line 106, in __init__
    this = _YamCha.new_Chunker(argc)
ValueError: List items must be strings`

What am I missing here? Kindly help me.

**Setup:**
All commands ran under virtual environment
**Python** : 3.7.6
**yamcha** - 0.33
**swig** - 3.0.12

**Comment by kavin26** [comment]
@kento1218 could you please guide me here?

**Comment by kento1218** [comment]
@kavin26 Yamcha is not maintained since 2005 by Taku K. originally. And I did just some small changes over 7 years ago. Sorry I have no idea what's happening on your side.
I think it's better to find new tool to achieve your purpose (maybe POS tagging or segmentation). There should be nicer one.
